apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"nginx-nginx-ingress-7ccd849c68-2vrqk","leaseDurationSeconds":30,"acquireTime":"2023-02-24T18:45:36Z","renewTime":"2023-02-24T18:50:00Z","leaderTransitions":0}'
  creationTimestamp: "2023-02-24T18:45:36Z"
  name: nginx-nginx-ingress-leader-election
  namespace: nginx
  resourceVersion: "82061"
  uid: 0f7d2a15-ab55-402b-8467-6ce90461997b
